import type { NodeTemplate, Workflow, WorkflowEdge, WorkflowNode } from "./types";

export const nodeTemplates: NodeTemplate[] = [
  // Triggers
  {
    type: "trigger",
    label: "Webhook",
    description: "Receive HTTP requests to trigger workflow",
    icon: "Webhook",
    color: "emerald",
    category: "triggers",
    configFields: [
      {
        key: "method",
        label: "HTTP Method",
        type: "select",
        options: ["GET", "POST", "PUT", "DELETE"],
        defaultValue: "POST",
      },
      { key: "path", label: "Path", type: "text", placeholder: "/api/webhook" },
      {
        key: "auth",
        label: "Auth Type",
        type: "select",
        options: ["None", "API Key", "Bearer Token"],
        defaultValue: "None",
      },
    ],
  },
  {
    type: "trigger",
    label: "Schedule",
    description: "Run on a cron schedule",
    icon: "Clock",
    color: "emerald",
    category: "triggers",
    configFields: [
      { key: "cron", label: "Cron Expression", type: "text", placeholder: "0 */6 * * *" },
      {
        key: "timezone",
        label: "Timezone",
        type: "select",
        options: ["UTC", "America/New_York", "Europe/London"],
        defaultValue: "UTC",
      },
    ],
  },
  {
    type: "trigger",
    label: "Manual",
    description: "Manually trigger this workflow",
    icon: "Hand",
    color: "emerald",
    category: "triggers",
    configFields: [],
  },

  // Browser Actions
  {
    type: "browser",
    label: "Navigate",
    description: "Navigate to a URL",
    icon: "Globe",
    color: "violet",
    category: "browser",
    configFields: [
      { key: "url", label: "URL", type: "text", placeholder: "https://example.com" },
      {
        key: "waitUntil",
        label: "Wait Until",
        type: "select",
        options: ["load", "domcontentloaded", "networkidle"],
        defaultValue: "load",
      },
      { key: "timeout", label: "Timeout (ms)", type: "number", defaultValue: 30000 },
    ],
  },
  {
    type: "browser",
    label: "Click Element",
    description: "Click on a page element",
    icon: "MousePointer",
    color: "violet",
    category: "browser",
    configFields: [
      { key: "selector", label: "CSS Selector", type: "text", placeholder: "#submit-button" },
      { key: "waitAfter", label: "Wait After (ms)", type: "number", defaultValue: 1000 },
    ],
  },
  {
    type: "browser",
    label: "Type Text",
    description: "Type text into an input field",
    icon: "Type",
    color: "violet",
    category: "browser",
    configFields: [
      { key: "selector", label: "CSS Selector", type: "text", placeholder: "input[name='email']" },
      { key: "text", label: "Text to Type", type: "text", placeholder: "hello@example.com" },
      { key: "delay", label: "Typing Delay (ms)", type: "number", defaultValue: 50 },
    ],
  },
  {
    type: "browser",
    label: "Extract Data",
    description: "Extract data from the page",
    icon: "Download",
    color: "violet",
    category: "browser",
    configFields: [
      { key: "selector", label: "CSS Selector", type: "text", placeholder: ".product-title" },
      {
        key: "attribute",
        label: "Attribute",
        type: "select",
        options: ["text", "href", "src", "innerHTML"],
        defaultValue: "text",
      },
      { key: "multiple", label: "Extract Multiple", type: "toggle", defaultValue: true },
    ],
  },
  {
    type: "browser",
    label: "Screenshot",
    description: "Take a screenshot of the page",
    icon: "Camera",
    color: "violet",
    category: "browser",
    configFields: [
      { key: "fullPage", label: "Full Page", type: "toggle", defaultValue: false },
      { key: "format", label: "Format", type: "select", options: ["png", "jpeg"], defaultValue: "png" },
      { key: "quality", label: "Quality", type: "number", defaultValue: 90 },
    ],
  },
  {
    type: "browser",
    label: "Wait For",
    description: "Wait for element or condition",
    icon: "Hourglass",
    color: "violet",
    category: "browser",
    configFields: [
      { key: "selector", label: "CSS Selector", type: "text", placeholder: ".loading" },
      { key: "timeout", label: "Timeout (ms)", type: "number", defaultValue: 10000 },
      { key: "hidden", label: "Wait for Hidden", type: "toggle", defaultValue: false },
    ],
  },

  // Logic
  {
    type: "condition",
    label: "If/Else",
    description: "Branch based on condition",
    icon: "GitBranch",
    color: "amber",
    category: "logic",
    configFields: [
      { key: "variable", label: "Variable", type: "text", placeholder: "{{step1.output}}" },
      {
        key: "operator",
        label: "Operator",
        type: "select",
        options: ["equals", "not equals", "contains", "greater than", "less than", "exists"],
      },
      { key: "value", label: "Value", type: "text", placeholder: "expected value" },
    ],
  },
  {
    type: "condition",
    label: "Loop",
    description: "Iterate over a collection",
    icon: "Repeat",
    color: "amber",
    category: "logic",
    configFields: [
      { key: "items", label: "Items Variable", type: "text", placeholder: "{{step1.output}}" },
      { key: "maxIterations", label: "Max Iterations", type: "number", defaultValue: 100 },
    ],
  },

  // AI
  {
    type: "agent",
    label: "AI Extract",
    description: "Use AI to extract structured data",
    icon: "Brain",
    color: "orange",
    category: "ai",
    configFields: [
      {
        key: "goal",
        label: "Extraction Goal",
        type: "textarea",
        placeholder: "Extract product name, price, and rating from the page",
      },
      {
        key: "model",
        label: "AI Model",
        type: "select",
        options: ["gpt-4o", "claude-3.5-sonnet", "gpt-4o-mini"],
        defaultValue: "gpt-4o-mini",
      },
      {
        key: "schema",
        label: "Output Schema (JSON)",
        type: "textarea",
        placeholder: '{"name": "string", "price": "number"}',
      },
    ],
  },
  {
    type: "agent",
    label: "AI Decide",
    description: "Let AI make a decision",
    icon: "Sparkles",
    color: "orange",
    category: "ai",
    configFields: [
      { key: "prompt", label: "Decision Prompt", type: "textarea", placeholder: "Should we proceed with this action?" },
      { key: "context", label: "Context Variables", type: "text", placeholder: "{{step1.output}}, {{step2.output}}" },
    ],
  },

  // Actions
  {
    type: "action",
    label: "HTTP Request",
    description: "Make an HTTP request",
    icon: "Send",
    color: "blue",
    category: "actions",
    configFields: [
      {
        key: "method",
        label: "Method",
        type: "select",
        options: ["GET", "POST", "PUT", "DELETE", "PATCH"],
        defaultValue: "GET",
      },
      { key: "url", label: "URL", type: "text", placeholder: "https://api.example.com/data" },
      {
        key: "headers",
        label: "Headers (JSON)",
        type: "textarea",
        placeholder: '{"Content-Type": "application/json"}',
      },
      { key: "body", label: "Body", type: "textarea" },
    ],
  },
  {
    type: "action",
    label: "Set Variable",
    description: "Set a workflow variable",
    icon: "Variable",
    color: "blue",
    category: "actions",
    configFields: [
      { key: "name", label: "Variable Name", type: "text", placeholder: "myVariable" },
      { key: "value", label: "Value", type: "text", placeholder: "{{step1.output}}" },
    ],
  },
  {
    type: "action",
    label: "Delay",
    description: "Wait for a specified duration",
    icon: "Timer",
    color: "blue",
    category: "actions",
    configFields: [{ key: "duration", label: "Duration (ms)", type: "number", defaultValue: 1000 }],
  },
  {
    type: "action",
    label: "JavaScript Code",
    description: "Run custom JavaScript",
    icon: "Code",
    color: "blue",
    category: "actions",
    configFields: [{ key: "code", label: "Code", type: "textarea", placeholder: "return input.data.toUpperCase();" }],
  },

  // Output
  {
    type: "output",
    label: "Send Email",
    description: "Send an email notification",
    icon: "Mail",
    color: "slate",
    category: "output",
    configFields: [
      { key: "to", label: "To", type: "text", placeholder: "user@example.com" },
      { key: "subject", label: "Subject", type: "text", placeholder: "Workflow Complete" },
      { key: "body", label: "Body", type: "textarea" },
    ],
  },
  {
    type: "output",
    label: "Slack Message",
    description: "Send a Slack notification",
    icon: "MessageSquare",
    color: "slate",
    category: "output",
    configFields: [
      { key: "channel", label: "Channel", type: "text", placeholder: "#general" },
      { key: "message", label: "Message", type: "textarea", placeholder: "Workflow completed!" },
    ],
  },
  {
    type: "output",
    label: "Save to Database",
    description: "Save data to database",
    icon: "Database",
    color: "slate",
    category: "output",
    configFields: [
      { key: "table", label: "Table", type: "text", placeholder: "products" },
      { key: "data", label: "Data Variable", type: "text", placeholder: "{{step1.output}}" },
    ],
  },
];

export const sampleNodes: WorkflowNode[] = [
  {
    id: "1",
    type: "trigger",
    label: "Webhook Trigger",
    description: "Receives incoming HTTP POST requests",
    config: { method: "POST", path: "/api/scrape", auth: "API Key" },
    status: "idle",
    duration: "0ms",
  },
  {
    id: "2",
    type: "browser",
    label: "Navigate to Page",
    description: "Opens the target URL in a stealth browser",
    config: { url: "https://shop.example.com/products", waitUntil: "networkidle", timeout: 15000 },
    status: "idle",
    duration: "2.3s",
  },
  {
    id: "3",
    type: "browser",
    label: "Wait for Content",
    description: "Waits for product grid to load",
    config: { selector: ".product-grid", timeout: 10000 },
    status: "idle",
    duration: "1.1s",
  },
  {
    id: "4",
    type: "condition",
    label: "Has Products?",
    description: "Checks if any products were found",
    config: { variable: "{{step3.output}}", operator: "exists" },
    status: "idle",
  },
  {
    id: "5",
    type: "agent",
    label: "AI Extract Products",
    description: "Uses AI to extract structured product data",
    config: {
      goal: "Extract name, price, rating, and image URL for each product",
      model: "gpt-4o-mini",
      schema: '{"name": "string", "price": "number", "rating": "number"}',
    },
    status: "idle",
    duration: "4.2s",
  },
  {
    id: "6",
    type: "action",
    label: "Save to Database",
    description: "Stores extracted products in database",
    config: { table: "products", data: "{{step5.output}}" },
    status: "idle",
    duration: "0.8s",
  },
  {
    id: "7",
    type: "output",
    label: "Slack Notification",
    description: "Sends completion notification to Slack",
    config: { channel: "#scraping", message: "Successfully scraped {{step5.output.length}} products" },
    status: "idle",
    duration: "0.3s",
  },
];

export const sampleEdges: WorkflowEdge[] = [
  { id: "e1-2", source: "1", target: "2", type: "default" },
  { id: "e2-3", source: "2", target: "3", type: "default" },
  { id: "e3-4", source: "3", target: "4", type: "default" },
  { id: "e4-5", source: "4", target: "5", type: "yes", label: "yes" },
  { id: "e5-6", source: "5", target: "6", type: "default" },
  { id: "e6-7", source: "6", target: "7", type: "default" },
];

export const sampleWorkflows: Workflow[] = [
  {
    id: "1",
    name: "Product Scraper",
    description: "Scrape product data from e-commerce sites with AI extraction",
    status: "active",
    nodes: sampleNodes,
    edges: sampleEdges,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
    lastRun: "2 min ago",
    runCount: 142,
  },
  {
    id: "2",
    name: "Form Auto-Fill",
    description: "Automatically fill job applications using AI",
    status: "draft",
    nodes: [],
    edges: [],
    createdAt: "2024-01-18",
    updatedAt: "2024-01-18",
    lastRun: "Never",
    runCount: 0,
  },
  {
    id: "3",
    name: "Price Monitor",
    description: "Track price changes across competitors daily",
    status: "paused",
    nodes: [],
    edges: [],
    createdAt: "2024-01-10",
    updatedAt: "2024-01-19",
    lastRun: "1 hr ago",
    runCount: 89,
  },
  {
    id: "4",
    name: "Lead Enrichment",
    description: "Enrich leads with company data from LinkedIn",
    status: "active",
    nodes: [],
    edges: [],
    createdAt: "2024-01-12",
    updatedAt: "2024-01-20",
    lastRun: "5 min ago",
    runCount: 234,
  },
];

export const templateCategories = [
  { id: "triggers", label: "Triggers", description: "Start your workflow" },
  { id: "browser", label: "Browser", description: "Browser automation" },
  { id: "logic", label: "Logic", description: "Flow control" },
  { id: "ai", label: "AI", description: "AI-powered actions" },
  { id: "actions", label: "Actions", description: "General actions" },
  { id: "output", label: "Output", description: "Send results" },
] as const;
