export { AppSidebar } from "./dashboard/sidebar/app-sidebar";
export { NavMain, type NavBadge, type NavGroup, type NavMainItem, type NavSubItem } from "./dashboard/sidebar/nav-main";
export { NavUser } from "./dashboard/sidebar/nav-user";
export { NavDocuments } from "./dashboard/sidebar/nav-documents";
export { NavSecondary } from "./dashboard/sidebar/nav-secondary";
export { SearchDialog, type NavGroup as SearchDialogNavGroup, type NavMainItem as SearchDialogNavMainItem } from "./dashboard/sidebar/search-dialog";
export { SidebarSupportCard } from "./dashboard/sidebar/sidebar-support-card";
export { LayoutControls } from "./dashboard/sidebar/layout-controls";
export { ThemeSwitcher } from "./dashboard/sidebar/theme-switcher";
export { AccountSwitcher } from "./dashboard/sidebar/account-switcher";
export { MetricCards } from "./dashboard/default/metric-cards";
export { PerformanceOverview } from "./dashboard/default/performance-overview";
export { SubscriberOverview } from "./dashboard/default/subscriber-overview";
export { recentCustomersSchema, type RecentCustomerRow } from "./dashboard/default/recent-customers-table/schema";
export { recentCustomersColumns } from "./dashboard/default/recent-customers-table/columns";
export { RecentCustomersTable } from "./dashboard/default/recent-customers-table/table";
export { SimpleIcon } from "./components/simple-icon";
export { DateRangePicker } from "./components/date-range-picker";
export { EventCalendarViews } from "./components/event-calendar-views";
export { sidebarItems, type NavGroup as SidebarNavGroup, type NavMainItem as SidebarNavMainItem } from "./navigation/sidebar-items";
